=== SenorBeso/assignment-1--databases--cs-365--fall-2024/xml/student.dtd
<!-- The root element is university, which contatins one or more student elements-->
<!ELEMENT university (student)+>

<!--A student element is comprised of one name, contact, program-info,
 and academics-info elements-->
<!ELEMENT student           (name,contact,program-info,academics-info)>

<!-- A name is comprised of the following elements:
a first-name, middle-name, last-name, and a preferred name-->
<!ELEMENT name              (first-name,middle-name,last-name,preferred-name)>
<!ELEMENT first-name        (#PCDATA)>
<!ELEMENT middle-name       (#PCDATA)>
<!ELEMENT last-name         (#PCDATA)>
<!ELEMENT preferred-name    (#PCDATA)>

<!--A contact element must contain an email and phone-->
<!ELEMENT contact           (email,phone)>
<!ELEMENT email             (#PCDATA)>
<!ELEMENT phone             (#PCDATA)>

<!--The program info element is consisted of a major, a minor, and an advisor-->
<!ELEMENT program-info      (major,minor,advisor)>
<!ELEMENT major             (#PCDATA)>
<!ELEMENT minor             (#PCDATA)>
<!ELEMENT advisor           (#PCDATA)>

<!--Academics info element is made up of their id number, their GPA,
their progression-status, their status, their intial enrollment, and graduation date-->
<!ELEMENT academics-info    (id,GPA,progression-status,status,intial-enrollment,graduation-date)>
<!ELEMENT id                (#PCDATA)>
<!ELEMENT GPA               (#PCDATA)>
<!ELEMENT progression-status (#PCDATA)>
<!ELEMENT status            (#PCDATA)>
<!ELEMENT intial-enrollment (#PCDATA)>
<!ELEMENT graduation-date   (#PCDATA)>

<!-- This requires that a name be inputted for a student-->
<!ATTLIST student
  first-name  CDATA #REQUIRED
  last-name   CDATA #REQUIRED>

<!--This attribute allows the only options to be added to status be the year,
and not a random string-->
<!ATTLIST progression-status
          progression_status (first-year|second-year|third-year|fourth-year) #REQUIRED>

<!--Similarly, this only allows these specific statuses to be inputted-->
<!ATTLIST status
          status (full-time|part-time|graduated|withdrawn) #REQUIRED>

=== SenorBeso/assignment-1--databases--cs-365--fall-2024/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE university SYSTEM "student.dtd">

<university>
<student first-name="Gordon" last-name="Sumner">
  <name>
    <first-name>Gordon</first-name>
    <middle-name>Matthew</middle-name>
    <last-name>Sumner</last-name>
    <preferred-name>Sting</preferred-name>
  </name>
  <contact>
    <email>sting@thepolice.com</email>
    <phone>212.123.4567</phone>
  </contact>
  <program-info>
    <major>Music</major>
    <minor>English</minor>
    <advisor>Andy Summers</advisor>
  </program-info>
  <academics-info>
    <id>1234567</id>
    <GPA>4.0</GPA>
    <progression-status>first year</progression-status>
    <status>full-time</status>
    <intial-enrollment>08-25-1969</intial-enrollment>
    <graduation-date>05-01-1973</graduation-date>
  </academics-info>
</student>
  <student first-name="Kim" last-name="Thayil">
    <name>
      <first-name>Kim</first-name>
      <middle-name></middle-name>
      <last-name>Thayil</last-name>
      <preferred-name></preferred-name>
    </name>
    <contact>
      <email>kim@soundgarden.com</email>
      <phone>206.123.4567</phone>
    </contact>
    <program-info>
      <major>Music</major>
      <minor>Criminal Justice</minor>
      <advisor>Chris Cornell</advisor>
    </program-info>
    <academics-info>
      <id>8302438</id>
      <GPA>3.0</GPA>
      <progression-status>second year</progression-status>
      <status>full-time</status>
      <intial-enrollment>08-25-1978</intial-enrollment>
      <graduation-date>05-01-1982</graduation-date>
    </academics-info>
  </student>
</university>
